language: java
sudo: false
install: true

jdk:
  - oraclejdk8

rvm:
  - 2.2

script: 
  - mvn clean install
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
